# THIS IS FOR DEV ONLY
version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  nats:
    command: ["--jetstream", "-n", "penguin-reports" ]
    image: nats
    restart: always
    ports:
      - "4222:4222"

volumes:
  postgres-data:
